### ISSUE TITLE
Reflect the status of canaries back to the template as conditions

### ISSUE THREAD

**Issue by moshloop** [flanksource/template-operator#30]
i.e. the Postgres operator comes with 2 canaries which would result in a status of:

```yaml
status:
   conditions:
     - reason:                Ready
        status:                True
        type:                  Postgres
     - type: s3Bucket
 ```
