### ISSUE TITLE
Templates failing to convert values missing from spec to appropriate nil type

### ISSUE THREAD

**Issue by flanksaul** [flanksource/template-operator#48]
When passing values from DependencyMatrix to Service, missing values do not covert to their appropriate nil type:

```yaml
apiVersion: templating.flanksource.com/v1
kind: Template
metadata:
  name: dependencymatrix-template
spec:
  source:
    apiVersion: services.domain.io/v1
    kind: DependencyMatrix
  resources:
    - forEach: "{{.spec.services}}"
      apiVersion: services.domain.io/v1
      kind: Service
      metadata:
        name: "{{.each.key}}"
        namespace: "{{.metadata.namespace}}"
      spec:
        image: "{{.each.key}}:{{.each.value.version}}"
        replicas: "{{.each.value.replicas }}"
        resources:
          heap: 
            minMB: "{{.each.value.resources.heap.minMB}}"
            maxMB: "{{.each.value.resources.heap.maxMB}}"
```

The following error is issued in the template-operator logs:

```
ts=2021-06-01T13:59:48.154713698Z level=error logger=controllers.Template msg="failed to ducktype object" template=/dependencymatrix-template error="failed to duck type object: failed to transform string to type &{[integer] }: strconv.Atoi: parsing \"<no value>\": invalid syntax" errorVerbose="strconv.Atoi: parsing \"<no value>\": invalid syntax\nfailed to transform string to type &{[integer] }
```

The Resources type is shared by both DependencyMatrix & Service CRDs

```go
type Heap struct {
	MinMB int `json:"minMB,omitempty"`
	MaxMB int `json:"maxMB,omitempty"`
}

type Resources struct {
	Heap Heap                        `json:"heap,omitempty"`
	CPU  corev1.ResourceRequirements `json:"cpu,omitempty"`
}
```

I'm expecting to be able to pass the following Service custom resource manifest – the cpu fields have similar issues:

```yaml
apiVersion: services.domain.io/v1
kind: Service
metadata:
  name: quote
  namespace: <somenamespace>
spec:
  image: <someimagename>
  replicas: 10
  resources: 
    heap:
        minMB: 100
        maxMB: 200
    cpu: 
        limits: 1000m
        requests: 100m
```
