### ISSUE TITLE
Source: GitRepository

### ISSUE THREAD

**Issue by moshloop** [flanksource/template-operator#66]
````yaml
source:
      gitRepository:
          namespace: flux
          name: ref-to-git-repo
          glob: "/grafana/dashboards/*.json"
resources:
  -      
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  name: " {{.filename}}"
  labels:
    app: grafana
spec:
  json:  "{{ .content }}

```
